#!/bin/sh

dir=`git rev-parse --git-dir`
if [ $? -gt 0 ]; then
    echo "Couldn't find .git, bailing"
    exit 1
else
    echo "Installing hooks to: $dir"
fi

for hook in post-receive; do
    echo "Installing hook: $hook"
    curl -s -S "https://raw.github.com/richo/git_template/master/hooks/$hook" > "$dir/hooks/$hook"
    chmod +x "$dir/hooks/$hook"
done

echo "Setting up auto_checkout"
touch "$dir/auto_checkout"
