#!/bin/sh

for i in *; do
    if [ "$i" = "bin" ] || [ "$i" = "code"]; then
        ln -s i ~/$i
    else
        if [ -f ~/.$i ]; then
            rm -i $i
        fi
        ln -s i ~/.$i
    fi
done

