#!/bin/sh

here=$(basename `pwd`)
for i in *; do
    if [ "$i" = "bin" ] || [ "$i" = "code" ]; then
        ln -s $here/$i ~/$i
    else
        echo $ARGV
        if [ -f ~/.$i ]; then
          rm -i $i
        fi
        if [ -L ~/.$i ]; then
          rm -i $i
        fi
        ln -s $here/$i ~/.$i
    fi
done

