#!/bin/sh
GITPATH=./

mkdir -p $GITPATH

data="fugitive  git://github.com/tpope/vim-fugitive.git             git\
    rails-vim   git://github.com/tpope/vim-rails.git                git\
    rvm-vim    git://github.com/tpope/vim-rvm.git                   git\
    jellybeans git@github.com:richoH/jellybeans.vim.git             git\
    fuzzy-finder git://github.com/richoH/FuzzyFinder.git            git\
    comment-object git@github.com:ConradIrwin/vim-comment-object.git git\
    markdown git://github.com/plasticboy/vim-markdown.git           git\
    l9        git://github.com/vim-scripts/L9.git                   git\
    gist      git://github.com/mattn/gist-vim.git                   git\
    matchit   git://github.com/vim-scripts/matchit.zip.git          git\
    nerd-tree git://github.com/vim-scripts/The-NERD-tree.git        git\
    commentary git://github.com/tpope/vim-commentary.git            git\
    unimpaired git://github.com/tpope/vim-unimpaired.git            git\
    vim-todo    git@github.com:richoH/vim-todo.git                  git
"
